# Docker-compose file to launch the web app.
version: '2'

volumes:
  db-data:
    driver: local

services:

  db:
    image: postgres:9.6
    container_name: pydaygal-db
    volumes:
      - db-data:/var/lib/postgresql
    env_file: .env
    networks:
      - back-tier

  webapp:
    build:
      context: .
      dockerfile: compose/webapp/Dockerfile
    image: pydaygal/webapp
    container_name: pydaygal-webapp
    command: /gunicorn.sh
    volumes:
      - .:/app
    depends_on:
      - db
    env_file: .env
    networks:
      - back-tier

  nginx:
    build:
      context: .
      dockerfile: compose/nginx/Dockerfile
    image: pydaygal/nginx
    container_name: pydaygal-nginx
    volumes:
      - ./public:/public
      - ./pydaygal/media:/media
    ports:
      - "5002:5002"
    depends_on:
      - webapp
    networks:
      - front-tier
      - back-tier

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
